plugins {
    id 'com.android.application'
}

android {
    compileSdk rootProject.ext.compileSdkVersion
    
    defaultConfig {
        applicationId "io.github.danielytbr.audiovisualizer"
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    // Core AndroidX
    implementation "androidx.core:androidx-core:${rootProject.ext.androidx_core_version}"
    implementation "androidx.appcompat:appcompat:${rootProject.ext.androidx_appcompat_version}"
    
    // Material Design
    implementation "com.google.android.material:material:${rootProject.ext.material_version}"
    
    // Constraint Layout
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
